config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: %i[create destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/user:id', to: 'users#show', as: 'user'
  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task

  validates :name, presence: true, length: { maximum: 10 }
  validates :comment, presence: true, length: { maximum: 1000 }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :comments
  has_one_attached :image
  before_validation :set_nameless_name
  validate :validate_name_not_including_comma

  belongs_to :user 

  scope :recent, -> { order(created_at: :desc) }

  def self.ransackable_attributes(auto_object = nil)
    %w[name]
  end 

  def self.ransackable_associations(auto_object = nil)
    []
  end 

  

  private

  def set_nameless_name
    self.name = '名前なし' if name.blank?
  end 

  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end 
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
    end

    def require_admin
      redirect_to root_url unless current_user.admin?
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :login_required
    
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end 

  def login_required
    redirect_to login_url unless current_user
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = 'コメントを投稿しました'
      redirect_to comment.task
    else
      redirect_back fallback_location: tasks_path, flash: {
      comment: comment, 
      error_messages: comment.errors.full_messages
      }
    end
  end 

  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to comment.task, flash: { notice: 'コメントが削除されました' }
  end

  private

  def comment_params
    params.require(:comment).permit(:task_id, :name, :comment)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page])
  end 

  def show
    @comment = Comment.new(task_id: @task.id)
  end

  def new
    @task = Task.new(flash[:task])
  end

  def edit
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      TaskMailer.creation_email(@task).deliver_now
      redirect_to @task, notice: "質問「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end 

  def update
    @task.update!(task_params)
    redirect_to tasks_url, notice: "質問「#{@task.name}」を更新しました。"
  end 

  def destroy
    @task.destroy
  end 

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end 

  private

  def task_params
    params.require(:task).permit(:name, :description, :image)
  end 

  def set_task
    @task = current_user.tasks.find(params[:id])
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end 
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.admin ? 'あり' : 'なし'
        td= user.created_at
        td= user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
.profile-wrap
  .row
    .col-md4.text-center
      = image_tag avatar_url(@user), class: "round-img"
    .col-md-8
      .row
        h1= @user.name
        = link_to "プロフィール編集", edit_admin_user_path, class: "btn btn-outline-dark common-btn edit-profile-btn" 
        botton.setting[type="botton" data-toggle="modal" data-target="#exampleModal"]

        #exampleModal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="exampleMolalLabel" aria-hidden="true"]
          .modal-dialog[role="document"]  
            .modal-content
              .modal-header
                h5#exampleModalLabel.modal-title
                 | 設定
                botton.close[type="botton" data-dismiss="modal" aria-label="Close"]
              .list-group.text-center
      - if @user == current_user
        .row
          p
            = @user.email
                    

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/comments/_comment.html.slim
.p-comment__item
  p = simple_format(comment.comment) 
  .p-comment__bottomLine
    span = comment.name 
    span = comment.created_at.to_s(:datetime_jp) 
    span = link_to '削除', comment, method: :delete, data: { confirm: '削除してもよろしいですか>' }

app/views/comments/_form.html.slim
= render 'shared/error_messages'

.p-comment__formBox
  .p-comment__formTitle コメント記入
  = form_for comment do |f| 
    = f.hidden_field :task_id 
    .form-group
      = f.label :name, '名前' 
      = f.text_field :name, class: 'form-control' 
    .form-group
      = f.label :comment, 'コメント' 
      = f.text_area :comment, class: 'form-control', rows: 4 
    = f.submit '送信', class: 'btn btn-primary' 

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | native
    
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .application.navbar.navbar-expand-md.p-3.fixed-top style="background-color:#3366CC;"
      .navbar-brand
      h2 native

      nav.navbar.navbar-light
        span.navbar-text 
          | 毎日５つのフレーズを覚えよう
          = icon 'fas', 'crown'
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to 'Phrases', tasks_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'Me', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'Bye', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'btn btn-info'
      
    .container
      - if flash.notice.present?
        .alert.alert-warning= flash.notice
      = yield
      script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
      script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
      script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li = message

= render 'shared/error_messages'

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/destroy.js.erb
document.querySelector("#task-<%= @task.id %>").style.display = "none";

app/views/tasks/edit.html.slim
h1 フレーズの編集

.nav.justify-content-end
  = link_to 'Pharases', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1 フレーズ一覧
= search_form_for @q, class: 'mb-5' do |f|
    = f.label :name_cont, 'Keyword'  
    = f.search_field :name_cont
    = f.submit class: 'btn btn-outline-dark'  

= link_to '新規登録', new_task_path, class: 'btn btn-outline-dark'

.mb-3
  table.table.table-hover
    thead.thead-default
      tr
        th= sort_link(@q, :name, default_order: :desc)
        th= Task.human_attribute_name(:created_at)
    tbody
      - @tasks.each do |task|
        tr id="task-#{task.id}"
          td= link_to task.name, task_path(task)
          td= task.created_at
          td
            = link_to '編集', edit_task_path(task), class: 'btn btn-outline-primary'
            = link_to '削除', task, method: :delete, remote: true, data: { confirm: "質問「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-outline-danger'

  = page_entries_info @tasks          
  = paginate @tasks
           

app/views/tasks/new.html.slim
h1 フレーズの新規登録

.nav.justify-content-end
  = link_to 'Phrases', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.slim
h1 フレーズの詳細

.nav.justify-content-end
  = link_to 'Phrases', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:description)
      td= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Task.human_attribute_name(:image)
      td= image_tag @task.image if @task.image.attached?
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

= link_to '編集', edit_task_path, class: 'btn btn-outline-dark'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

.p-comment__list
  .p-comment_listTitle 
    | コメント
    = render @task.comments

= render partial: 'comments/form', locals: { comment: @comment } 